CREATE TABLE note (
id INTEGER PRIMARY KEY AUTOINCREMENT,
author_id INTEGER,
title VARCHAR(128) NOT NULL,
content VARCHAR(128) NOT NULL,
created_on DATETIME,
FOREIGN KEY(author_id) REFERENCES author(id)
);

CREATE TABLE author (
id PRIMARY KEY AUTOINCREMENT,
name VARCHAR(128) NOT NULL
);