DROP TABLE IF EXISTS author;
CREATE TABLE author (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(128) NOT NULL
);

DROP TABLE IF EXISTS note;
CREATE TABLE note (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title VARCHAR(128) NOT NULL,
  content VARCHAR(128) NOT NULL,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  author_id INTEGER REFERENCES author(id)
);



