BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `artist` (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`name`	VARCHAR(128) NOT NULL

);
CREATE TABLE IF NOT EXISTS `album` (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`title`	VARCHAR(128) NOT NULL,
	`release_year`	INTEGER
);
COMMIT;
