CREATE TABLE album (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR(128) NOT NULL,
    release_year INTEGER
);

CREATE TABLE artist (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(128) NOT NULL
);

CREATE TABLE track (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR(128) NOT NULL,
    FOREIGN KEY (album_id) INTEGER REFERENCES album(id)
);

CREATE TABLE artist_album (
    FOREIGN KEY (artist_id) INTEGER REFERENCES artist(id),
    FOREIGN KEY (album_id) INTEGER REFERENCES album(id)
);

